import type { Metadata } from "next";
import clsx from "clsx";
import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Header = () => {
  return (
    <header>
      <Link href={"/"}>
        <h1 className="mb-5 text-2xl">Let's Go Developers</h1>
      </Link>
    </header>
  );
};

const Footer = () => {
  return (
    <footer className="bottom-0 absolute">
      <p>made with love</p>
    </footer>
  );
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx(inter.className, "min-h-screen flex flex-col")}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
